### PR TITLE
add delete icon on measurement item

### PR DESCRIPTION
**Pull request by m00n620**

### CODE REVIEW

**Review by Blackglade — CHANGES_REQUESTED** [review]
Can you remove the yarn lock file from the changes?

**Comment by m00n620** [comment]
> Can you remove the yarn lock file from the changes?

We should keep `yarn.lock` changes as we have changes in `package.json` in sub packages(for now, nl-pacs), do you have any issues from this `yarn.lock`?

**Comment by Blackglade** [comment]
> > Can you remove the yarn lock file from the changes?
> 
> We should keep `yarn.lock` changes as we have changes in `package.json` in sub packages(for now, nl-pacs), do you have any issues from this `yarn.lock`?

Nevermind I was under the impression that any `package.json` changes for sub packages (`nl-pacs`) and the associated `yarn.lock` file wouldn't affect the top-level `yarn.lock` file for `nl-ohif`, but apparently it does.

**Comment by shivasuri** [comment]
Should we add these changes to `nl-ohif-modules`?

**Comment by m00n620** [comment]
Screenshot 2023-05-04 060306
@shivasuri , @Blackglade , please take a look

**Pull request merged**
